name: release

on: workflow_dispatch

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission to gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Set up Environment Variables
        id: env-vars
        run: echo "##[set-output name=modversion;]$(grep 'mod_version' gradle.properties | cut -f2- -d=)"
      - name: Install changelog parser
        uses: taiki-e/install-action@parse-changelog
      - name: Parse changelog
        run: parse-changelog CHANGELOG.md ${{ steps.env-vars.outputs.modversion }} > changes.md
      - uses: Kir-Antipov/mc-publish@v3.1
        with:
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          changelog-file: changes.md